# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'windows-latest'

steps:
- powershell: write-host 'Hello world'
  displayName: Say hello
  workingDirectory: $(build.sourcesDirectory)
  failOnStderr: true
